apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
  labels:
    app: hello-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
      - name: hello-app
        image: us.icr.io/jauninb-kube-razee/hello-razee-ct:16-master-03d3d03c-20201127124059
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 32Mi
            cpu: 125m
          requests:
            memory: 32Mi
            cpu: 125m
