apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
  labels:
    app: hello-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
      - name: hello-app
        image: us.icr.io/jauninb-kube-razee/hello-razee-ct:9-master-8340c501-20201029113129
        ports:
        - containerPort: 8080
